#define INITIAL_DECODE_BARRIER 1
#define INITIAL_DECODE_MIN_LATENCY_S_RATIO 80.0
#define INITIAL_DECODE_MIN_SAVINGS_TRANSFERS 3.0
#define INITIAL_DECODE_REQUIRE_MONOTONIC 1
#include "layered_scheduler.cpp"
