#define INITIAL_DECODE_BARRIER 1
#define INITIAL_DECODE_MIN_LATENCY_S_RATIO 80.0
#define INITIAL_DECODE_MIN_SAVINGS_TRANSFERS 3.0
#define INITIAL_DECODE_REQUIRE_MONOTONIC 1
#define INITIAL_DECODE_MAX_READY_FRACTION 0.25
#define DYNAMIC_COHERENT_DISPERSION_RATIO 0.15
#define DYNAMIC_COHERENT_MAX_GROUP 8
#include "layered_scheduler.cpp"
