#define OBJECTIVE_MARGIN_ROLLOUT 1
#define OBJECTIVE_MARGIN_ROLLOUT_THRESHOLD 0.03
#define OBJECTIVE_MARGIN_MIN_LATENCY_WEIGHT 0.0
#define OBJECTIVE_MARGIN_MIN_URGENCY 0.75
#include "v83_conservative_neural_policy.cpp"
